version: 2

formats:
   - epub
   - pdf

build:
  image: latest

python:
  version: 3.7
  install:
     - method: pip
       path: .
       extra_requirements: docs
  system_packages: true

sphinx:
  builder: html
  configuration: conf.py
  fail_on_warning: true
