language: python
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

python:
- 3.7
- 3.6

matrix:
  include:
  - os: osx
    language: minimal
    addons:
      homebrew:
        packages:
        - python3
    before_install: pip3 install pytest
    install: pip3 install -e .[tests,full]
  - os: linux
    python: 3.5
    before_install: pip install matplotlib==2.2.4
  - os: linux
    python: 3.4
    before_install: pip install matplotlib==2.2.4
  - os: linux
    python: 2.7
    before_install: pip install matplotlib==2.2.4
 # - os: linux
 #   python: 3.7
 #   install: pip install -e .[tests,full,cov]
 #   script:
 #   - flake8
 #   - mypy .
 #   after_success:
 #   - pytest --cov
 #   - coveralls

install: pip install -e .[tests,full]

script: pytest -rsv
