language: python
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

python:
- 3.7
- 3.6
- 3.5
- 3.4
- 2.7

matrix:
  include:
  - os: osx
    language: minimal
    addons:
      homebrew:
        packages:
        - python3
    install: pip3 install -e .[tests,full]
  - os: linux
    python: 3.5
    before_install:
    - pip install -U setuptools
    - pip install -U pip
 # - os: linux
 #   python: 3.7
 #   install: pip install -e .[tests,full,cov]
 #   script:
 #   - flake8
 #   - mypy .
 #   after_success:
 #   - pytest --cov
 #   - coveralls


install: pip install -e .[tests,full]

script: pytest -rsv
